package com.bird.dao;

import com.bird.model.entity.Attachment;
import com.bird.model.entity.AttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    long countByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int deleteByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insert(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insertSelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    List<Attachment> selectByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    Attachment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Attachment record, @Param("example") AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Attachment record, @Param("example") AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByPrimaryKey(Attachment record);
}