package com.bird.dao;

import com.bird.model.entity.Inform;
import com.bird.model.entity.InformExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    long countByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int deleteByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insert(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insertSelective(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    List<Inform> selectByExampleWithBLOBs(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    List<Inform> selectByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    Inform selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Inform record, @Param("example") InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Inform record, @Param("example") InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Inform record, @Param("example") InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByPrimaryKeyWithBLOBs(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByPrimaryKey(Inform record);
}