package com.bird.dao;

import com.bird.model.entity.StaffActionLog;
import com.bird.model.entity.StaffActionLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StaffActionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    long countByExample(StaffActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int deleteByExample(StaffActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insert(StaffActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insertSelective(StaffActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    List<StaffActionLog> selectByExample(StaffActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    StaffActionLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") StaffActionLog record, @Param("example") StaffActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExample(@Param("record") StaffActionLog record, @Param("example") StaffActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(StaffActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByPrimaryKey(StaffActionLog record);
}