package com.bird.dao;

import com.bird.model.entity.SystemPermissionNode;
import com.bird.model.entity.SystemPermissionNodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemPermissionNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_PERMISSION_NODE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    long countByExample(SystemPermissionNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_PERMISSION_NODE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int deleteByExample(SystemPermissionNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_PERMISSION_NODE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_PERMISSION_NODE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insert(SystemPermissionNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_PERMISSION_NODE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insertSelective(SystemPermissionNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_PERMISSION_NODE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    List<SystemPermissionNode> selectByExample(SystemPermissionNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_PERMISSION_NODE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    SystemPermissionNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_PERMISSION_NODE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") SystemPermissionNode record, @Param("example") SystemPermissionNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_PERMISSION_NODE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExample(@Param("record") SystemPermissionNode record, @Param("example") SystemPermissionNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_PERMISSION_NODE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(SystemPermissionNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_PERMISSION_NODE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByPrimaryKey(SystemPermissionNode record);
}