package com.bird.dao;

import com.bird.model.entity.SystemRoute;
import com.bird.model.entity.SystemRouteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemRouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    long countByExample(SystemRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int deleteByExample(SystemRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insert(SystemRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insertSelective(SystemRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    List<SystemRoute> selectByExample(SystemRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    SystemRoute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") SystemRoute record, @Param("example") SystemRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExample(@Param("record") SystemRoute record, @Param("example") SystemRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(SystemRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByPrimaryKey(SystemRoute record);
}