package com.bird.dao;

import com.bird.model.entity.SystemRouteRole;
import com.bird.model.entity.SystemRouteRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemRouteRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE_ROLE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    long countByExample(SystemRouteRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE_ROLE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int deleteByExample(SystemRouteRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE_ROLE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insert(SystemRouteRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE_ROLE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int insertSelective(SystemRouteRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE_ROLE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    List<SystemRouteRole> selectByExample(SystemRouteRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE_ROLE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") SystemRouteRole record, @Param("example") SystemRouteRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYSTEM_ROUTE_ROLE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    int updateByExample(@Param("record") SystemRouteRole record, @Param("example") SystemRouteRoleExample example);
}