package com.bird.model.entity;

import java.io.Serializable;
import java.util.Date;

public class Attachment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ATTACHMENT.id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ATTACHMENT.sequence
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ATTACHMENT.file_name
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ATTACHMENT.file_path
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ATTACHMENT.upload_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Date uploadDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ATTACHMENT.uploader
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer uploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ATTACHMENT.status
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ATTACHMENT.deleter
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer deleter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ATTACHMENT.delete_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Date deleteDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ATTACHMENT.real_file_name
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String realFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ATTACHMENT.file_size
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ATTACHMENT
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ATTACHMENT.id
     *
     * @return the value of T_ATTACHMENT.id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ATTACHMENT.id
     *
     * @param id the value for T_ATTACHMENT.id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ATTACHMENT.sequence
     *
     * @return the value of T_ATTACHMENT.sequence
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ATTACHMENT.sequence
     *
     * @param sequence the value for T_ATTACHMENT.sequence
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setSequence(String sequence) {
        this.sequence = sequence == null ? null : sequence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ATTACHMENT.file_name
     *
     * @return the value of T_ATTACHMENT.file_name
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ATTACHMENT.file_name
     *
     * @param fileName the value for T_ATTACHMENT.file_name
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ATTACHMENT.file_path
     *
     * @return the value of T_ATTACHMENT.file_path
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ATTACHMENT.file_path
     *
     * @param filePath the value for T_ATTACHMENT.file_path
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ATTACHMENT.upload_date
     *
     * @return the value of T_ATTACHMENT.upload_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ATTACHMENT.upload_date
     *
     * @param uploadDate the value for T_ATTACHMENT.upload_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ATTACHMENT.uploader
     *
     * @return the value of T_ATTACHMENT.uploader
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ATTACHMENT.uploader
     *
     * @param uploader the value for T_ATTACHMENT.uploader
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setUploader(Integer uploader) {
        this.uploader = uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ATTACHMENT.status
     *
     * @return the value of T_ATTACHMENT.status
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ATTACHMENT.status
     *
     * @param status the value for T_ATTACHMENT.status
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ATTACHMENT.deleter
     *
     * @return the value of T_ATTACHMENT.deleter
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getDeleter() {
        return deleter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ATTACHMENT.deleter
     *
     * @param deleter the value for T_ATTACHMENT.deleter
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setDeleter(Integer deleter) {
        this.deleter = deleter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ATTACHMENT.delete_date
     *
     * @return the value of T_ATTACHMENT.delete_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Date getDeleteDate() {
        return deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ATTACHMENT.delete_date
     *
     * @param deleteDate the value for T_ATTACHMENT.delete_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ATTACHMENT.real_file_name
     *
     * @return the value of T_ATTACHMENT.real_file_name
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getRealFileName() {
        return realFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ATTACHMENT.real_file_name
     *
     * @param realFileName the value for T_ATTACHMENT.real_file_name
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setRealFileName(String realFileName) {
        this.realFileName = realFileName == null ? null : realFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ATTACHMENT.file_size
     *
     * @return the value of T_ATTACHMENT.file_size
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ATTACHMENT.file_size
     *
     * @param fileSize the value for T_ATTACHMENT.file_size
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }
}