package com.bird.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InformExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public InformExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTopIsNull() {
            addCriterion("top is null");
            return (Criteria) this;
        }

        public Criteria andTopIsNotNull() {
            addCriterion("top is not null");
            return (Criteria) this;
        }

        public Criteria andTopEqualTo(Boolean value) {
            addCriterion("top =", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopNotEqualTo(Boolean value) {
            addCriterion("top <>", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopGreaterThan(Boolean value) {
            addCriterion("top >", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopGreaterThanOrEqualTo(Boolean value) {
            addCriterion("top >=", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopLessThan(Boolean value) {
            addCriterion("top <", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopLessThanOrEqualTo(Boolean value) {
            addCriterion("top <=", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopIn(List<Boolean> values) {
            addCriterion("top in", values, "top");
            return (Criteria) this;
        }

        public Criteria andTopNotIn(List<Boolean> values) {
            addCriterion("top not in", values, "top");
            return (Criteria) this;
        }

        public Criteria andTopBetween(Boolean value1, Boolean value2) {
            addCriterion("top between", value1, value2, "top");
            return (Criteria) this;
        }

        public Criteria andTopNotBetween(Boolean value1, Boolean value2) {
            addCriterion("top not between", value1, value2, "top");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Integer value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Integer value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Integer value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Integer value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Integer value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Integer> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Integer> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Integer value1, Integer value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Integer value1, Integer value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andAttchmentListIsNull() {
            addCriterion("attchment_list is null");
            return (Criteria) this;
        }

        public Criteria andAttchmentListIsNotNull() {
            addCriterion("attchment_list is not null");
            return (Criteria) this;
        }

        public Criteria andAttchmentListEqualTo(String value) {
            addCriterion("attchment_list =", value, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andAttchmentListNotEqualTo(String value) {
            addCriterion("attchment_list <>", value, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andAttchmentListGreaterThan(String value) {
            addCriterion("attchment_list >", value, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andAttchmentListGreaterThanOrEqualTo(String value) {
            addCriterion("attchment_list >=", value, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andAttchmentListLessThan(String value) {
            addCriterion("attchment_list <", value, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andAttchmentListLessThanOrEqualTo(String value) {
            addCriterion("attchment_list <=", value, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andAttchmentListLike(String value) {
            addCriterion("attchment_list like", value, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andAttchmentListNotLike(String value) {
            addCriterion("attchment_list not like", value, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andAttchmentListIn(List<String> values) {
            addCriterion("attchment_list in", values, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andAttchmentListNotIn(List<String> values) {
            addCriterion("attchment_list not in", values, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andAttchmentListBetween(String value1, String value2) {
            addCriterion("attchment_list between", value1, value2, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andAttchmentListNotBetween(String value1, String value2) {
            addCriterion("attchment_list not between", value1, value2, "attchmentList");
            return (Criteria) this;
        }

        public Criteria andCancelerIsNull() {
            addCriterion("canceler is null");
            return (Criteria) this;
        }

        public Criteria andCancelerIsNotNull() {
            addCriterion("canceler is not null");
            return (Criteria) this;
        }

        public Criteria andCancelerEqualTo(Integer value) {
            addCriterion("canceler =", value, "canceler");
            return (Criteria) this;
        }

        public Criteria andCancelerNotEqualTo(Integer value) {
            addCriterion("canceler <>", value, "canceler");
            return (Criteria) this;
        }

        public Criteria andCancelerGreaterThan(Integer value) {
            addCriterion("canceler >", value, "canceler");
            return (Criteria) this;
        }

        public Criteria andCancelerGreaterThanOrEqualTo(Integer value) {
            addCriterion("canceler >=", value, "canceler");
            return (Criteria) this;
        }

        public Criteria andCancelerLessThan(Integer value) {
            addCriterion("canceler <", value, "canceler");
            return (Criteria) this;
        }

        public Criteria andCancelerLessThanOrEqualTo(Integer value) {
            addCriterion("canceler <=", value, "canceler");
            return (Criteria) this;
        }

        public Criteria andCancelerIn(List<Integer> values) {
            addCriterion("canceler in", values, "canceler");
            return (Criteria) this;
        }

        public Criteria andCancelerNotIn(List<Integer> values) {
            addCriterion("canceler not in", values, "canceler");
            return (Criteria) this;
        }

        public Criteria andCancelerBetween(Integer value1, Integer value2) {
            addCriterion("canceler between", value1, value2, "canceler");
            return (Criteria) this;
        }

        public Criteria andCancelerNotBetween(Integer value1, Integer value2) {
            addCriterion("canceler not between", value1, value2, "canceler");
            return (Criteria) this;
        }

        public Criteria andCancelDateIsNull() {
            addCriterion("cancel_date is null");
            return (Criteria) this;
        }

        public Criteria andCancelDateIsNotNull() {
            addCriterion("cancel_date is not null");
            return (Criteria) this;
        }

        public Criteria andCancelDateEqualTo(Date value) {
            addCriterion("cancel_date =", value, "cancelDate");
            return (Criteria) this;
        }

        public Criteria andCancelDateNotEqualTo(Date value) {
            addCriterion("cancel_date <>", value, "cancelDate");
            return (Criteria) this;
        }

        public Criteria andCancelDateGreaterThan(Date value) {
            addCriterion("cancel_date >", value, "cancelDate");
            return (Criteria) this;
        }

        public Criteria andCancelDateGreaterThanOrEqualTo(Date value) {
            addCriterion("cancel_date >=", value, "cancelDate");
            return (Criteria) this;
        }

        public Criteria andCancelDateLessThan(Date value) {
            addCriterion("cancel_date <", value, "cancelDate");
            return (Criteria) this;
        }

        public Criteria andCancelDateLessThanOrEqualTo(Date value) {
            addCriterion("cancel_date <=", value, "cancelDate");
            return (Criteria) this;
        }

        public Criteria andCancelDateIn(List<Date> values) {
            addCriterion("cancel_date in", values, "cancelDate");
            return (Criteria) this;
        }

        public Criteria andCancelDateNotIn(List<Date> values) {
            addCriterion("cancel_date not in", values, "cancelDate");
            return (Criteria) this;
        }

        public Criteria andCancelDateBetween(Date value1, Date value2) {
            addCriterion("cancel_date between", value1, value2, "cancelDate");
            return (Criteria) this;
        }

        public Criteria andCancelDateNotBetween(Date value1, Date value2) {
            addCriterion("cancel_date not between", value1, value2, "cancelDate");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorIsNull() {
            addCriterion("outdate_operator is null");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorIsNotNull() {
            addCriterion("outdate_operator is not null");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorEqualTo(Integer value) {
            addCriterion("outdate_operator =", value, "outdateOperator");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorNotEqualTo(Integer value) {
            addCriterion("outdate_operator <>", value, "outdateOperator");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorGreaterThan(Integer value) {
            addCriterion("outdate_operator >", value, "outdateOperator");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("outdate_operator >=", value, "outdateOperator");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorLessThan(Integer value) {
            addCriterion("outdate_operator <", value, "outdateOperator");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorLessThanOrEqualTo(Integer value) {
            addCriterion("outdate_operator <=", value, "outdateOperator");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorIn(List<Integer> values) {
            addCriterion("outdate_operator in", values, "outdateOperator");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorNotIn(List<Integer> values) {
            addCriterion("outdate_operator not in", values, "outdateOperator");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorBetween(Integer value1, Integer value2) {
            addCriterion("outdate_operator between", value1, value2, "outdateOperator");
            return (Criteria) this;
        }

        public Criteria andOutdateOperatorNotBetween(Integer value1, Integer value2) {
            addCriterion("outdate_operator not between", value1, value2, "outdateOperator");
            return (Criteria) this;
        }

        public Criteria andOutdateDateIsNull() {
            addCriterion("outdate_date is null");
            return (Criteria) this;
        }

        public Criteria andOutdateDateIsNotNull() {
            addCriterion("outdate_date is not null");
            return (Criteria) this;
        }

        public Criteria andOutdateDateEqualTo(Date value) {
            addCriterion("outdate_date =", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateNotEqualTo(Date value) {
            addCriterion("outdate_date <>", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateGreaterThan(Date value) {
            addCriterion("outdate_date >", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("outdate_date >=", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateLessThan(Date value) {
            addCriterion("outdate_date <", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateLessThanOrEqualTo(Date value) {
            addCriterion("outdate_date <=", value, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateIn(List<Date> values) {
            addCriterion("outdate_date in", values, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateNotIn(List<Date> values) {
            addCriterion("outdate_date not in", values, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateBetween(Date value1, Date value2) {
            addCriterion("outdate_date between", value1, value2, "outdateDate");
            return (Criteria) this;
        }

        public Criteria andOutdateDateNotBetween(Date value1, Date value2) {
            addCriterion("outdate_date not between", value1, value2, "outdateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_INFORM
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}