package com.bird.model.entity;

import java.io.Serializable;
import java.util.Date;

public class Inform implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.title
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.top
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Boolean top;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.create_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.status
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.creator
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.attchment_list
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String attchmentList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.canceler
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer canceler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.cancel_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Date cancelDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.outdate_operator
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer outdateOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.outdate_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Date outdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INFORM.content
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_INFORM
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.id
     *
     * @return the value of T_INFORM.id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.id
     *
     * @param id the value for T_INFORM.id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.title
     *
     * @return the value of T_INFORM.title
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.title
     *
     * @param title the value for T_INFORM.title
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.top
     *
     * @return the value of T_INFORM.top
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Boolean getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.top
     *
     * @param top the value for T_INFORM.top
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setTop(Boolean top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.create_date
     *
     * @return the value of T_INFORM.create_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.create_date
     *
     * @param createDate the value for T_INFORM.create_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.status
     *
     * @return the value of T_INFORM.status
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.status
     *
     * @param status the value for T_INFORM.status
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.creator
     *
     * @return the value of T_INFORM.creator
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.creator
     *
     * @param creator the value for T_INFORM.creator
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.attchment_list
     *
     * @return the value of T_INFORM.attchment_list
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getAttchmentList() {
        return attchmentList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.attchment_list
     *
     * @param attchmentList the value for T_INFORM.attchment_list
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setAttchmentList(String attchmentList) {
        this.attchmentList = attchmentList == null ? null : attchmentList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.canceler
     *
     * @return the value of T_INFORM.canceler
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getCanceler() {
        return canceler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.canceler
     *
     * @param canceler the value for T_INFORM.canceler
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setCanceler(Integer canceler) {
        this.canceler = canceler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.cancel_date
     *
     * @return the value of T_INFORM.cancel_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Date getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.cancel_date
     *
     * @param cancelDate the value for T_INFORM.cancel_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.outdate_operator
     *
     * @return the value of T_INFORM.outdate_operator
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getOutdateOperator() {
        return outdateOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.outdate_operator
     *
     * @param outdateOperator the value for T_INFORM.outdate_operator
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setOutdateOperator(Integer outdateOperator) {
        this.outdateOperator = outdateOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.outdate_date
     *
     * @return the value of T_INFORM.outdate_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Date getOutdateDate() {
        return outdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.outdate_date
     *
     * @param outdateDate the value for T_INFORM.outdate_date
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setOutdateDate(Date outdateDate) {
        this.outdateDate = outdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INFORM.content
     *
     * @return the value of T_INFORM.content
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INFORM.content
     *
     * @param content the value for T_INFORM.content
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}