package com.bird.model.entity;

import java.io.Serializable;
import java.util.Date;

public class StaffActionLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.staff_account
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String staffAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.staff_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.request_uri
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String requestUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.request_time
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Date requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.request_source_ip
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String requestSourceIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.request_method
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String requestMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.request_body
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String requestBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.controller_method
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String controllerMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.error_message
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String errorMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.success
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Boolean success;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.handling_time
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer handlingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.response_time
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Date responseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.response
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String response;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ACTION_LOG.des
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_STAFF_ACTION_LOG
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.id
     *
     * @return the value of T_STAFF_ACTION_LOG.id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.id
     *
     * @param id the value for T_STAFF_ACTION_LOG.id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.staff_account
     *
     * @return the value of T_STAFF_ACTION_LOG.staff_account
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getStaffAccount() {
        return staffAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.staff_account
     *
     * @param staffAccount the value for T_STAFF_ACTION_LOG.staff_account
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setStaffAccount(String staffAccount) {
        this.staffAccount = staffAccount == null ? null : staffAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.staff_id
     *
     * @return the value of T_STAFF_ACTION_LOG.staff_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.staff_id
     *
     * @param staffId the value for T_STAFF_ACTION_LOG.staff_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.request_uri
     *
     * @return the value of T_STAFF_ACTION_LOG.request_uri
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getRequestUri() {
        return requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.request_uri
     *
     * @param requestUri the value for T_STAFF_ACTION_LOG.request_uri
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setRequestUri(String requestUri) {
        this.requestUri = requestUri == null ? null : requestUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.request_time
     *
     * @return the value of T_STAFF_ACTION_LOG.request_time
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.request_time
     *
     * @param requestTime the value for T_STAFF_ACTION_LOG.request_time
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.request_source_ip
     *
     * @return the value of T_STAFF_ACTION_LOG.request_source_ip
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getRequestSourceIp() {
        return requestSourceIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.request_source_ip
     *
     * @param requestSourceIp the value for T_STAFF_ACTION_LOG.request_source_ip
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setRequestSourceIp(String requestSourceIp) {
        this.requestSourceIp = requestSourceIp == null ? null : requestSourceIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.request_method
     *
     * @return the value of T_STAFF_ACTION_LOG.request_method
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.request_method
     *
     * @param requestMethod the value for T_STAFF_ACTION_LOG.request_method
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod == null ? null : requestMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.request_body
     *
     * @return the value of T_STAFF_ACTION_LOG.request_body
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.request_body
     *
     * @param requestBody the value for T_STAFF_ACTION_LOG.request_body
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody == null ? null : requestBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.controller_method
     *
     * @return the value of T_STAFF_ACTION_LOG.controller_method
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getControllerMethod() {
        return controllerMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.controller_method
     *
     * @param controllerMethod the value for T_STAFF_ACTION_LOG.controller_method
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setControllerMethod(String controllerMethod) {
        this.controllerMethod = controllerMethod == null ? null : controllerMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.error_message
     *
     * @return the value of T_STAFF_ACTION_LOG.error_message
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.error_message
     *
     * @param errorMessage the value for T_STAFF_ACTION_LOG.error_message
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage == null ? null : errorMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.success
     *
     * @return the value of T_STAFF_ACTION_LOG.success
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Boolean getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.success
     *
     * @param success the value for T_STAFF_ACTION_LOG.success
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setSuccess(Boolean success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.handling_time
     *
     * @return the value of T_STAFF_ACTION_LOG.handling_time
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getHandlingTime() {
        return handlingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.handling_time
     *
     * @param handlingTime the value for T_STAFF_ACTION_LOG.handling_time
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setHandlingTime(Integer handlingTime) {
        this.handlingTime = handlingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.response_time
     *
     * @return the value of T_STAFF_ACTION_LOG.response_time
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Date getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.response_time
     *
     * @param responseTime the value for T_STAFF_ACTION_LOG.response_time
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.response
     *
     * @return the value of T_STAFF_ACTION_LOG.response
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.response
     *
     * @param response the value for T_STAFF_ACTION_LOG.response
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ACTION_LOG.des
     *
     * @return the value of T_STAFF_ACTION_LOG.des
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ACTION_LOG.des
     *
     * @param des the value for T_STAFF_ACTION_LOG.des
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }
}