package com.bird.model.entity;

import java.io.Serializable;

public class StaffRoleKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ROLE.staff_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ROLE.role_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_STAFF_ROLE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ROLE.staff_id
     *
     * @return the value of T_STAFF_ROLE.staff_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ROLE.staff_id
     *
     * @param staffId the value for T_STAFF_ROLE.staff_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ROLE.role_id
     *
     * @return the value of T_STAFF_ROLE.role_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ROLE.role_id
     *
     * @param roleId the value for T_STAFF_ROLE.role_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}