package com.bird.model.entity;

import java.io.Serializable;

public class StaffRole extends StaffRoleKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_STAFF_ROLE.des
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_STAFF_ROLE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_STAFF_ROLE.des
     *
     * @return the value of T_STAFF_ROLE.des
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_STAFF_ROLE.des
     *
     * @param des the value for T_STAFF_ROLE.des
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }
}