package com.bird.model.entity;

import java.io.Serializable;

public class SystemSequence extends SystemSequenceKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYSTEM_SEQUENCE.sequence
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYSTEM_SEQUENCE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYSTEM_SEQUENCE.sequence
     *
     * @return the value of T_SYSTEM_SEQUENCE.sequence
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYSTEM_SEQUENCE.sequence
     *
     * @param sequence the value for T_SYSTEM_SEQUENCE.sequence
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }
}