package com.bird.model.entity;

import java.io.Serializable;

public class SystemRouteRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYSTEM_ROUTE_ROLE.route_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYSTEM_ROUTE_ROLE.role_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYSTEM_ROUTE_ROLE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYSTEM_ROUTE_ROLE.route_id
     *
     * @return the value of T_SYSTEM_ROUTE_ROLE.route_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYSTEM_ROUTE_ROLE.route_id
     *
     * @param routeId the value for T_SYSTEM_ROUTE_ROLE.route_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYSTEM_ROUTE_ROLE.role_id
     *
     * @return the value of T_SYSTEM_ROUTE_ROLE.role_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYSTEM_ROUTE_ROLE.role_id
     *
     * @param roleId the value for T_SYSTEM_ROUTE_ROLE.role_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}