package com.bird.model.entity;

import java.io.Serializable;

public class SystemPermissionRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYSTEM_PERMISSION_ROLE.role_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYSTEM_PERMISSION_ROLE.permission_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private Integer permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYSTEM_PERMISSION_ROLE
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYSTEM_PERMISSION_ROLE.role_id
     *
     * @return the value of T_SYSTEM_PERMISSION_ROLE.role_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYSTEM_PERMISSION_ROLE.role_id
     *
     * @param roleId the value for T_SYSTEM_PERMISSION_ROLE.role_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYSTEM_PERMISSION_ROLE.permission_id
     *
     * @return the value of T_SYSTEM_PERMISSION_ROLE.permission_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYSTEM_PERMISSION_ROLE.permission_id
     *
     * @param permissionId the value for T_SYSTEM_PERMISSION_ROLE.permission_id
     *
     * @mbg.generated Wed Nov 13 05:06:51 GMT+08:00 2019
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
}